In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
PCMR_cm = pd.read_csv('./PCMR(cms)_JB4.CSV')

In [3]:
PCMR_ml = pd.read_csv('./PCMR(mls)_JB4.CSV')

In [4]:
PCMR_SIGBF = pd.read_csv('./PCMR(SIG)_JB4.CSV')

In [5]:
PCMR_SIG = pd.read_csv('./PCMR(SIGBF)_JB4.CSV')

In [6]:
PCMR_cm = PCMR_cm.transpose()
PCMR_cm.rename(columns=PCMR_cm.iloc[0],inplace=True)
PCMR_cm = PCMR_cm.drop(PCMR_cm.index[0])
PCMR_cm

,5,10,20,40,60,80,100,125,160,170,200,220,250,300,350,400,150_1,150_2,150_3,150_4
4mm,1.62,0.69,2.61,3.02,3.65,4.09,5.11,4.7,5.57,6.88,6.44,10.72,8.32,13.18,12.18,14.51,4.38,6.04,5.81,5.5
8mm,0.75,1.74,1.53,2.89,3.02,3.96,4.58,5.11,6.31,6.88,7.8,8.7,9.7,11,12.1,14.04,5.96,5.49,5.61,5.62
6.5mm,1.81,1.46,1.69,3.23,4.37,5.69,5.04,5.6,7.16,5.43,7.46,8.24,8.95,11.25,12.14,12.47,2.45,4.82,7.39,6.18
11mm,1.13,1.38,1.88,2.54,2.96,3.76,4.18,5.17,5.89,6.29,7.53,8.43,9.29,11.24,13.25,14.67,4.67,5.6,5.45,5.36

In [7]:
PCMR_ml = PCMR_ml.transpose()
PCMR_ml.rename(columns=PCMR_ml.iloc[0],inplace=True)
PCMR_ml = PCMR_ml.drop(PCMR_ml.index[0])
PCMR_ml

,5,10,20,40,60,80,100,125,160,170,200,220,250,300,350,400,150_1,150_2,150_3,150_4
4mm,0.13,0.06,0.25,0.3,0.36,0.41,0.56,0.51,0.61,0.75,0.7,1.15,0.9,1.4,1.34,1.36,0.43,0.63,0.56,0.54
8mm,0.27,0.73,0.64,1.29,1.34,1.79,2.06,2.32,2.69,3.07,3.43,3.83,4.53,5.03,5.73,6.59,2.67,2.72,2.59,2.51
6.5mm,0.46,0.42,0.5,0.92,1.32,1.74,1.61,1.83,2.04,1.64,2.09,2.6,2.71,3.52,3.7,4.08,0.77,1.49,2.3,1.83
11mm,0.9,1.13,1.62,2.07,2.5,3.23,3.4,4.26,5.02,5.54,6.3,7,8.13,10.01,11.39,12.75,4.04,4.76,4.5,4.52

In [8]:
PCMR_SIGBF = PCMR_SIGBF.transpose()
PCMR_SIGBF.rename(columns=PCMR_SIGBF.iloc[0],inplace=True)
PCMR_SIGBF = PCMR_SIGBF.drop(PCMR_SIGBF.index[0])
PCMR_SIGBF

,5,10,20,40,60,80,100,125,160,170,200,220,250,300,350,400,150_1,150_2,150_3,150_4
4mm,1.018,0.815,1.145,1.236,1.328,1.375,1.415,1.385,1.429,1.48,1.488,1.487,1.501,1.472,1.478,1.479,1.36,1.431,1.416,1.401
8mm,0.131,0.48,0.721,0.865,0.957,1.049,1.101,1.123,1.219,1.26,1.296,1.259,1.312,1.328,1.318,1.31,1.164,1.137,1.113,1.127
6.5mm,0.501,0.52,0.71,0.932,1.05,1.1,1.115,1.139,1.191,1.184,1.233,1.188,1.225,1.245,1.229,1.22,0.742,1.007,1.125,1.105
11mm,0.405,0.429,0.646,0.799,0.899,0.997,1.029,1.066,1.181,1.226,1.263,1.262,1.311,1.344,1.354,1.343,1.062,1.084,1.064,1.062

In [9]:
PCMR_SIG = PCMR_SIG.transpose()
PCMR_SIG.rename(columns=PCMR_SIG.iloc[0],inplace=True)
PCMR_SIG = PCMR_SIG.drop(PCMR_SIG.index[0])
PCMR_SIG

,5,10,20,40,60,80,100,125,160,170,200,220,250,300,350,400,150_1,150_2,150_3,150_4
4mm,5.69,5.39,10.9,11.9,14.7,16.29,17.82,17.45,18.92,19.35,19.03,21.52,21,20.97,21.2,21.65,13.9,18.47,18.64,17.53
8mm,1.173,28.89,55.93,65.1,82,96.52,109.19,116.89,129.43,129.97,136.23,141.75,148.24,147.49,146.39,151.9,101.78,114.96,119.53,119.18
6.5mm,8.826,17.34,28.9,43.56,55.31,59.84,64.16,68.91,72.72,65.77,72.23,75.21,76.79,77.73,77.23,81.11,17.08,53.76,71.24,68.16
11mm,39.33,81.53,143.48,179.75,214.35,246.25,268.6,293.67,327.66,331.26,352.51,378.48,386.68,390.5,404.35,414.95,226.8,296.75,306.6,310.93